### ISSUE TITLE
[gzdoom] TNT - Map 08 - "wfall" animated textures

### ISSUE THREAD

**Issue by swc132994** [KuriKai/DHTP#18]
Hello,
found these on a play through on Map 08 on TNT

![2015-07-01_09-07-57](https://cloud.githubusercontent.com/assets/10770202/8450874/49fbf180-1fce-11e5-84ab-f6aca8ca66f7.png)
Original

![2015-07-01_09-09-27](https://cloud.githubusercontent.com/assets/10770202/8450879/56234fd0-1fce-11e5-93c8-83b38e4211c8.png)
Hires

Also the "slad" & "sladrip" textures look a little off on the edges

**Comment by KuriKai** [comment]
What is the texture name? do you have the dhtp loading correctly? I just loaded up the level in doomsday, and there was no problem

**Comment by swc132994** [comment]
using GZdoom latest build.
textures are "wfall1", "slad2", "sladrip1".

I first used the latest pack for Zdoom 
"zdoom-dhtp-20150623" however it was loading doom 1 textures over TNT therefore I broke the pack down into modules and loaded them in the correct order in the .ini file

![2015-07-01_13-20-04](https://cloud.githubusercontent.com/assets/10770202/8454254/920385c0-1feb-11e5-995b-1ea70e641a6a.png)
this is what I got from loading the "zdoom-dhtp-20150623" pack

**Comment by dread-marine** [comment]
Just crop blue area in wfall files, and it works.

**Comment by dread-marine** [comment]
About other animation glitches, it seems the easiest way is to extract all files in sub-folders doom1, doom2 etc. to main folder _hires_ (with overwrite) for each wad individually. I.e. you extract folder doom1 to hires, deleting other folders and save it, for example doom1_hires.pk3 and then start only with doom1.wad.

**Comment by swc132994** [comment]
Hi Dread-marine, thanks for the advice.
I edited the wfall textures and it does indeed look better and shows only the water portion now.

For myself I split the packs up into separate modules loading them in the .ini to get the loading correct so TNT images overwrite the doom1 versions.
![2015-08-03_09-20-10](https://cloud.githubusercontent.com/assets/10770202/9033696/154df23a-39b9-11e5-81c0-caa17c6e39a1.png)

If you look at the image above the slad & sladrip images look cut off at the beginning and crosses over into the next image.
I did a little investigating and took a look inside the map editor for this TNT level and noticed that on that original image there is an offset of 4 pixels for "slad2" and "slad1rip". Therefore I offset all the hires slad and sladrip images by x,16 pixels to see if this corrected the problem.

![2015-08-03_09-33-56](https://cloud.githubusercontent.com/assets/10770202/9033846/8303dad2-39ba-11e5-9dff-57cb7f9f0e58.png)

**Comment by KuriKai** [comment]
Are you guys able to report a bug to zdoom/gzdoom so that there is no need to split the pack up?

**Comment by swc132994** [comment]
I managed to get a topic posted in the GZDoom Dev forums:
http://forum.drdteam.org/viewtopic.php?f=22&t=6672

However admin have only allocated this in the general discussion and not the bugs forum

**Comment by KuriKai** [comment]
Hopefully he will notice it, you can't post in the bug subforum?

**Comment by swc132994** [comment]
I though I did post in the bugs sub forum, it must have been moved to general. I did get a response from the DRD team admin, you can see it in the link I posted but I will post it below as well:

by Eruanna » Fri Aug 07, 2015 10:05 
"Doom 1 textures are supposed to override Doom 2 textures, other than the skies. Doom 2 has a bunch of dummy switch textures that are placeholders for their Doom 1 counterparts and were only included to allow the executable to load. (It was really hacky, even for id Software, but it worked)

Other than that, try and extract Doom2's mapinfo from GZDoom.pk3 (it is mapinfo/doom2.txt) - rename it mapinfo.txt - and then change all references to "SKY1" to "RSKY1", "SKY2" to "RSKY2", and "SKY3" to "RSKY3" and it should (hopefully?) work a little better.

Not having the pack, myself, however, I do not know for sure. I just know that works for getting Doom 1 and Doom 2 to load simultaneously."

**Comment by KuriKai** [comment]
I responded to that post, with more info about the pack, hopefully it helps.
I have no idea why doom1 would overwrite doom2 textures, sounds crazy to me.

**Comment by KuriKai** [comment]
I have been directed to post a bug in the zdoom forums. 

I will create a list of the bugs listed here and post in the zdoom forums about it

**Comment by KuriKai** [comment]
Bug reported to zdoom forums
http://forum.zdoom.org/viewtopic.php?f=2&t=49322&p=853406#p853406

**Comment by KuriKai** [comment]
An udate
http://forum.zdoom.org/viewtopic.php?f=7&t=49322

**Comment by swc132994** [comment]
Ah, I see. There need to be filters in place for loading textures correctly.
I imagine that "filter/doom" is for all doom games and others will only apply to the specific games.

**Comment by KuriKai** [comment]
Can anyone test this?
http://forum.zdoom.org/viewtopic.php?f=7&t=49322#p853560

**Comment by dread-marine** [comment]
Any ideas how to enable this feature?

**Comment by KuriKai** [comment]
Create a pk3 with that format?

**Comment by Dranyth** [comment]
I realize this whole project is probably dead, but having recently gotten into Doom modding, I had run into this issue and from my research found that it had never been officially resolved.

I was using GZDoom with the first level of FreeDoom having a waterfall with the broken/flickering texture (WFALL1 and 4 I believe) while using the DHTP.  I experimented with different file structures inside of the .PK3, including the updated information about the filters in that ZDoom forum thread.  I came to the conclusion that GZDoom does not perform the filtering system upon resources retrieved from an archive.

The two possible solutions I came down to are: breaking each folder out into a separate archive (.PK3) and then utilizing the autoload system in the .INI to load each archive for the appropriate games.  To break out each folder into its own .PK3, you have to ensure that the textures reside within a folder called 'hires' inside of the archive or the engine will not recognize them at all.

The other method is to straight up unzip the DHTP into the GZDoom directory and reorganizing it into the <filter>/<game> filtering system.  The folder structure you should end up with using this method is:

> GZDoom\textures\doom
> GZDoom\textures\doom.doom2
> GZDoom\textures\doom.doom2.plutonia
> GZDoom\textures\doom.doom2.tnt

After making the filtered 'textures' folder discovery, I even tried to simply zip up the whole textures folder that was working into a new .PK3 and loading that, which would result in the game strangely taking the upper left corner of all of the textures and applying only as much of the texture to match the original resolution texture.  However, despite seeming to sort of do something, the waterfall texture showed the flickering that showed it was still ignoring the filter system and was loading the TNT version of the texture on top of the vanilla version.  Renaming the 'textures' folder to 'hires' did get the engine to correctly load the textures, but again, ignored the filter system to just load everything from the archive.

The proper solution is probably to break them out into their own archives, though curiously, the completely unzipped textures folder version seems to play a bit better with the engine.  For instance, in the Display Options>OpenGL Options>Texture Options, going to Enable HiRes Textures and turning it on and off does absolutely nothing when loading the hires textures from an archive, but will correctly toggle the textures between original and hires if loading from the 'textures' folder.

Hope this helps someone who comes looking for info about it in the future!

**Comment by KuriKai** [comment]
zdoom is pretty crap with external textures, it doesn't implement proper load order of textures.

So the best way is to unzip the pack into the hires texture folder?
if you can create a simple howto, i can put it on the download page for people to follow

**Comment by Dranyth** [comment]
It isn't even really a load order issue exactly, if they just used their own filtering system when importing from archives, it would never import those TNT textures when you weren't running TNT in the first place, for instance.

A 'hires' folder is only necessary for archives, in fact, it doesn't seem to work for loose files in the folder structure of the engine at all.

Basically you could reorganize the ZDoom version of the pack in two ways, either you could make a zip containing 4 separate .PK3 files, one that covers each game; for instance:
>zdoom-dhtp-20150723-doom.pk3
>zdoom-dhtp-20150723-doom-doom2.pk3
>zdoom-dhtp-20150723-doom-doom2-plutonia.pk3
>zdoom-dhtp-20150723-doom-doom2-tnt.pk3

(the names don't mean anything special to the engine, just for organizational sake, though in this case I have named the part after the date of the pack after the exact section of the autoload that PK3 needs to go into)
Each of these .PK3s would only contain a 'hires' folder that would have all of the textures that belong to that pack's game in it.  Users would unzip the archive to wherever they keep their addons, and would then need to add the path of each of the .PK3 files to the appropriate section of their INI file's autoload; i.e. zdoom-dhtp-20150723-doom.pk3's path would be added to the [doom.Autoload] section, zdoom-dhtp-20150723-doom-doom2.pk3's path would be added to the [doom.doom2.Autoload] section, etc.  This method is probably a cleaner way of doing it, but it does involve a little more work for the end user.  In this case, I suppose the Readme files could go into the root directory of the overall archive along with the 4 separate PK3s.


The other method, would be to take the current pack and reorganize it a bit with intent to be extracted, so you'd probably want to turn it back into a Zip instead of a PK3 (or use 7zip or whatever else to make it an archive) to make it clear that it isn't supposed to be loaded as is, and in fact would no longer work being loaded as a PK3.  Instead of the current file structure of:
>hires
>hires/doom2
>hires/doom2-plut
>hires/doom2-tnt

You would need to reorganize it into:
>textures
>textures/doom
>textures/doom.doom2
>textures/doom.doom2.plutonia
>textures/doom.doom2.tnt

(these folder names are critical to the engine's filtering system, so they must be named this, I believe it is case sensitive as well)

All of the loose files within the current pack's 'hires' folder would be moved to the 'doom' folder itself and the 'textures' folder would be essentially empty, only containing the filter-named folders.  I'm not entirely sure where the current Readme files would best go in this scenario, maybe in the 'textures' folder would work, or just the root level?  At any rate, this newly reorganized Zip (or RAR or 7z or whatever), would be downloaded and then need to be unzipped into the ZDoom/GZDoom main directory, nothing else would need to be done, the textures should just work at that point.

The second method is certainly easier for the end user, however it is potentially messier and tougher to clean up correctly if there are any other mods that want to put loose files into the 'textures' folder as well.


I know this is wordy, but hopefully it helps explain the situation fully.

**Comment by KuriKai** [comment]
that second method is easy enough to do, just need to change the compile script

**Comment by KuriKai** [comment]
https://mega.nz/#!NoIjVCrI!SV7iCMJAPuujoI1JP2PL6ZARHWSvhAWJpyyClHqm4Xk
Does this work?
Rename it to a .zip first then extract. the file structure should be correct

**Comment by Dranyth** [comment]
I saw this right when you posted it, sorry it took me a little while to answer, I was doing some testing with the pack and ran into some weirdness.

At first I thought it was working fine when extracted to the GZDoom folder, the hires textures seemed to be loaded.  Then I noticed that the floors (and perhaps ceilings?) were still using the low-res versions.  It became apparent when I used the OpenGL Enable Hires Textures option to turn them on and off in real time and noticed that while the walls' textures were changing obviously, the floors weren't changing at all.

I was basing some of my information off of the documentation at: http://zdoom.org/wiki/Using_ZIPs_as_WAD_replacement which is information that is also related at http://zdoom.org/wiki/Namespace .  Basically, the engine handles Flats completely separately from other Textures.  In light of this information, I did a quick experiment by creating a Flats folder in the base GZDoom folder, then put a Doom folder inside of that.  Then I went to the Textures/Doom folder and moved a bunch of files named ceil*, flat* and floor* over to the Flats/Doom folder and tried the game.  Sure enough, some of the floor and ceiling hires textures now loaded, though not all of them.

However, loading from a PK3 seems to somehow bypass this and filters the various file replacements to where they're supposed to go, despite being a mixture of textures and flats.  I'm actually really curious how the archive import even works, as it seems a bit weird.

It also doesn't explain why the 'hires' folder being in GZDoom's base folder doesn't result in any texture replacement at all, or why the 'textures' folder allows hires texture replacement to happen, based on what I read in the Namespace documentation.  This seems like a bit of an inconsistency on their end.

Regardless, unless you want to pull all Flats out into their own directory alongside Textures in the archive, keeping in mind that not all flats are named something with ceil, flat or floor in the filename, I think that puts us back around to method one from above, creating separate PK3 files for Doom, Doom2, Doom2 Plutonia and Doom2 TNT, and then relying on the autoloading sections to load them appropriately.

**Comment by KuriKai** [comment]
yeah zdoom doesn't do a very good job with external addons(the did a half arse attempt at copying doomsdays external texture format)

So which way will work?
can you provide a layout for me to follow and i will whip up another one for you to try.

**Comment by Dranyth** [comment]
As in method one, basically take all the files that are currently inside 'textures/doom', put them in a folder called 'hires' and just zip that folder up into something like zdoom-dhtp-20160806-doom.pk3.  Then take the files inside 'textures/doom.doom2' and put them in a 'hires' folder and zip that up into zdoom-dhtp-20160806-doom.doom2.pk3.  And repeat for the other two, which would be zdoom-dhtp-20160806-doom.doom2.plutonia.pk3 and zdoom-dhtp-20160806-doom.doom2.tnt.pk3.  Then you can take those 4 PK3s, along with your Readmes, and zip them up into zdoom-dhtp-20160806.zip and distribute that.

If you think some instruction should be packaged with them, or just put on the download page, let me know, but basically users would need to unzip the package where they want to keep their addons, then add the paths to each of the 4 PK3s into the appropriate section of their INI file's Autoload.

**Comment by KuriKai** [comment]
so it will end up like
zdoom-dhtp-20160806.zip
-hires/
-hires/zdoom-dhtp-20160806-doom.pk3 (contains flats alos)
-hires/zdoom-dhtp-20160806-doom.doom2.pk3 (doesn't contain flats)
-hires/zdoom-dhtp-20160806-doom.doom2-plutionia.pk3 (doesn't contain flats)
-hires/zdoom-dhtp-20160806-doom.doom2.tnt.pk3 (doesn't contain flats)
-readmewalls
-readmeflats

**Comment by Dranyth** [comment]
The top level Zip doesn't need a 'hires' folder, it would just have the PK3s and the Readmes in it at root level.  The individual PK3s need to have the 'hires' folders that the textures would all be inside.

**Comment by KuriKai** [comment]
if you could do the correct layout, like i did above(but correct) i can fully understand how it's supposed to be done. (i have never used zdoom)

**Comment by Dranyth** [comment]
Sure, it would just be:
>zdoom-dhtp-20160806.zip
>-zdoom-dhtp-20160806-doom.pk3
>-zdoom-dhtp-20160806-doom.doom2.pk3
>-zdoom-dhtp-20160806-doom.doom2.plutonia.pk3
>-zdoom-dhtp-20160806-doom.doom2.tnt.pk3
>-readme files

The individual PK3s would just be like:
>zdoom-dhtp-20160806-doom.pk3
>-hires/
>-hires/(all of the textures for doom)
 

>zdoom-dhtp-20160806-doom.doom2.pk3
>-hires/
>-hires/(all of the textures for doom2)
 

>zdoom-dhtp-20160806-doom.doom2.plutonia.pk3
>-hires/
>-hires/(all of the textures for the Plutonia pack)
 

>zdoom-dhtp-20160806-doom.doom2.tnt.pk3
>-hires/
>-hires/(all of the textures for the TNT pack)

I hope that clears it up.

**Comment by KuriKai** [comment]
ok, created it how you described(i hope) tell me if this works please
https://mega.nz/#!U8xUCaoQ!OtxQHaq9xvTUFjh1Dyx36TrkvczOyIFOYrbQYdS8LLg

**Comment by Dranyth** [comment]
Looks like it's working great!  I unzipped it into my GZDoom folder, went into my INI and added each file's path to the appropriate Autoload section, started up the game and all the hires textures were showing up just fine, including floors and ceilings.  And that was without any glitchy texture in the waterfall.

So I'd say it's a success!

**Comment by KuriKai** [comment]
awesome, can you write up instructions on how to install it? (step by step instructions/with example)
Then i will update the pack and release a new version for people

And will then close this issue

**Comment by Dranyth** [comment]
Installing the Doom High Resolution Texture Project for use in the ZDoom/GZDoom engine

As of the 2016/08/06 build, this version has been reorganized to address latent texture errors that occur as a result of the engine's method of loading and overwriting textures.  Because of this, the installation method has changed slightly.

After downloading the _zdoom-dhtp-20160806.zip_ (or later version), simply unzip the archive to wherever you wish to keep your add-ons.  The rest of this example will use **GZDoom** and will assume that the archive has been extracted into the base **GZDoom** directory.  You should end up with several Readme files and at least 4 PK3 files.

Once extracted, you'll need to open your _gzdoom-<username>.INI_ file in a text editor such as Notepad.    Here we will be adding each PK3 file's path into its respective Autoload section.  Scroll down to the section marked **[doom.Autoload]**, add a line return and then enter the path to the appropriate PK3 for that section.  It should look something like the following:
>**[doom.Autoload]**
>**Path=$PROGDIR/zdoom-dhtp-20160806-doom.pk3**

Scroll to the section marked **[doom.doom2.Autoload]** and repeat with the next file's path to end up with:
>**[doom.doom2.Autoload]**
>**Path=$PROGDIR/zdoom-dhtp-20160806-doom2.pk3**

Scroll to the section marked **[doom.doom2.plutonia.Autoload]** and repeat with the next file's path to end up with:
>**[doom.doom2.plutonia.Autoload]**
>**Path=$PROGDIR/zdoom-dhtp-20160806-doom2.plutonia.pk3**

And finally, scroll to the section marked **[doom.doom2.tnt.Autoload]** and repeat with the last file's path to end up with:
>**[doom.doom2.tnt.Autoload]**
>**Path=$PROGDIR/zdoom-dhtp-20160806-doom2.tnt.pk3**

Do note that load order within a section is important if a section contains paths to other resource packs already and that resources lower on a section's list can overwrite resources earlier in the list if they are trying to modify the same thing.

That's all there is to it!  Save the INI file and load up GZDoom to enjoy all of the high resolution textures available!

**Comment by Dranyth** [comment]
Hmm... I think that should work anyway.  I'm debating whether to add a caution for users to not simply add the paths for the 4 files into the [Global.Autoload], as some might be used to doing.  Putting all the files in the Global.Autoload would end up with the exact same texture overwrite issues that the current/old pack has.  I'm not sure if the warning is necessary.

**Comment by KuriKai** [comment]
Released the package and updated the download and installation pages

thanks for the bug troubleshooting
